# Generated by Django 5.0.7 on 2024-08-03 05:45

import django.core.validators
import referrals.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "tiff"]
                            ),
                            referrals.validators.validate_file_size,
                        ],
                    ),
                ),
                (
                    "product_value",
                    models.CharField(
                        choices=[
                            ("whatsapp", "Whatsapp"),
                            ("phone", "Phone"),
                            ("website", "Website"),
                        ],
                        default="website",
                        max_length=10,
                    ),
                ),
                ("product_link", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(1000000000)
                        ],
                    ),
                ),
                (
                    "traffic",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(1000000000)
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("superadmin", "Superadmin")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "support",
                    models.CharField(
                        choices=[("support", "Support"), ("suggestion", "Suggestion")],
                        default="support",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in-progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="in-progress",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="low",
                        max_length=15,
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="support_ticket_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "tiff", "pdf"]
                            ),
                            referrals.validators.validate_file_size,
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Ticket",
                "verbose_name_plural": "Support Tickets",
            },
        ),
        migrations.CreateModel(
            name="UserRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ranking_icons/",
                        validators=[referrals.validators.validate_file_size],
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
                ("rank_level", models.IntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("gold pro", "Gold Pro"),
                            ("gold", "Gold"),
                            ("silver pro", "Silver Pro"),
                            ("silver", "Silver"),
                            ("platinum", "Platinum"),
                        ],
                        default="silver",
                        max_length=15,
                    ),
                ),
                ("total_recruits", models.IntegerField(default=0)),
                ("bonus", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Ranking",
                "verbose_name_plural": "User Rankings",
            },
        ),
    ]
