# Generated by Django 5.0.8 on 2024-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0004_ticketreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pending_shares",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
