# Generated by Django 5.0.8 on 2024-08-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0004_individualprofile_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEarnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("description", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "earnings_type",
                    models.CharField(
                        choices=[
                            ("direct_referral", "Direct Referral"),
                            ("matching_bonus", "Matching Bonus"),
                            ("stairstep_bonus", "Stairstep Bonus"),
                            ("board_breaker_bonus", "Board Breaker Bonus"),
                            ("promote_and_earn_bonus", "Promote and Earn Bonus"),
                        ],
                        default="direct_referral",
                        max_length=55,
                    ),
                ),
                (
                    "individual_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="useraccounts.individualprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Earning",
                "verbose_name_plural": "Users Earnings",
            },
        ),
    ]
