# Generated by Django 5.0.8 on 2024-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0006_alter_userearnings_earnings_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userearnings",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
