# Generated by Django 5.0.8 on 2024-08-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0007_alter_userearnings_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
