# Generated by Django 5.0.8 on 2024-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0008_alter_customuser_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
