# Generated by Django 5.0.8 on 2024-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "useraccounts",
            "0009_alter_customuser_address_alter_customuser_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userearnings",
            name="earnings_type",
            field=models.CharField(
                choices=[
                    ("direct_referral_bonus", "Direct Referral Bonus"),
                    ("matching_bonus", "Matching Bonus"),
                    ("stairstep_bonus", "Stairstep Bonus"),
                    ("board_breaker_bonus", "Board Breaker Bonus"),
                    ("promote_and_earn_bonus", "Promote and Earn Bonus"),
                ],
                default="direct_referral_bonus",
                max_length=55,
            ),
        ),
    ]
