# Generated by Django 5.0.8 on 2024-08-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0010_alter_userearnings_earnings_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualprofile",
            name="membership_type",
            field=models.CharField(
                choices=[("individual package", "Individual Package")],
                default="individual package",
                max_length=20,
            ),
        ),
    ]
