# Generated by Django 5.0.8 on 2024-08-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0011_individualprofile_membership_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarningsType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bonus_name", models.CharField(max_length=100, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Earnings Type",
                "verbose_name_plural": "Earnings Types",
            },
        ),
    ]
