# Generated by Django 5.0.8 on 2024-08-23 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0012_earningstype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userearnings",
            name="earnings_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_earnings",
                to="useraccounts.earningstype",
            ),
        ),
    ]
